= Spring Boot Backend

== Installing

[,bash]
----
mvn clean package
----

== Running locally

First, start a database as described bellow.

[,bash]
----
mvn spring-boot:run
----

The application will be available at `http://localhost:8080`.

== How to run database

This will start an empty database. The schema will be created when started the application.

[,bash]
----
docker run -d -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_USER=backend -e POSTGRES_PASSWORD=backend -e POSTGRES_DB=backenddb -p 5432:5432 postgres:13
----

WARNING: the schema will be dropped and re-created each time the application starts.

To change this behavior, change the value of `spring.jpa.hibernante.ddl-auto` and `spring.datasource.initialization-mode` in the `application.yml` file.

== Some details

* Here will be placed all the necessary configuration for the application to run correctly.
** The `JwtAuthFitler` is necessary to read the JWT from the HTTP headers.
** The `PasswordConfig` is to encode and decode the passwords, to avoid having the passwords in plain text.
** The `SecurityConfig` contains the Spring Security 6 configuration, with the protected routes, exception handler and the http filters.
** The `UserAuthenticationEntryPoint` manages the exceptions.
** The `UserAuthenticationProvider` manages the authentication, creating the JWT or validating it.
** The `UsernamePasswordAuthFitler` is the filter which reads the username and password information.
** The `WebConfig` contains the CORS configuration.
* Controllers
** There are the two available controllers. One for the authentication and registration. And the other to access the protected ressources.
* Services
** Two services are available. One to authenticate a user, to verify the credentials. And the other service is to register a new user.
* Authenticaion
** The authentication is handled with a JWT.
** The application is stateless. This means that no session is managed by Spring, no data is stored in the session.
** Each request to protected resources must contain a JWT in the Authorization header to be accepted.
** Only two requests don't need the JWT, the login and the register. But both will generate a JWT after their action finishes correctly.
